### ISSUE TITLE
Request Queue Stopping main Queue

### ISSUE THREAD

**Issue by ShadowLordAlpha** [aiarena/aiarena-client#37] opened 2021-01-17 16:55 UTC
As we can see from the image below RStrelok has games waiting for it to play in the Main queue but it is currently playing in the request queue. This game in the request queue is stopping the other the other 1-6 AC that are waiting for a game to play from startting.

As the request queue does not save data back to the bot it should be ignored when the main queue checks if a bot is currently running and needs to save its data file back.

As we can see when MicroMachine was added to the request queue its games all started up right away becauase there were clients waiting so just the behavior between the queues needs to be looked at

![image](https://user-images.githubusercontent.com/4204089/104849935-b7b8f000-58a9-11eb-8649-929253d307f3.png)

**Comment by ShadowLordAlpha** [comment] 2021-01-17 17:09
Update: After the match managed to finish the main queue has started playing the matches again

**Comment by lladdy** [comment] 2022-03-20 11:46
I believe this has since been fixed in an update.
Ideally this should be confirmed by someone before we close the issue though.

**Comment by lladdy** [comment] 2022-03-20 12:33
![image](https://user-images.githubusercontent.com/14326310/159162431-70b2f2a2-60bc-496b-8fea-3ba9bef423be.png)
Yes looks like it has - been fixed - closing issue.

**Closed by lladdy** 2022-03-20 12:33 UTC
